# This Source Code Form is subject to the terms of the Mozilla Public
# License, v.2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import grpc
from client import embedding_store_pb2_grpc
from client import embedding_store_pb2


class EmbeddingStoreClient:
     """Creates client (new instance of the embedding store class) and establishes a connection.

    Args:
        self: A reference to the current instance of the class.
        host: The desired hostname
        port: The specified port number, set to 50051

    """
    def __init__(self, host="localhost", port=50051):
        connection_str = "%.%".format(host, port)
        self._channel = grpc.insecure_channel('localhost:50051')
        self._stub = embedding_store_pb2_grpc.EmbeddingStoreStub(self._channel)

    """Closes the connection.

    Args: 
        self: A reference to the current instance of the class.

    """
    def close(self):
        return self._channel.close()
    """Creates embedding record for storage.

    Creates a new embedding record that is stored with a Faiss generated index as the key.
    The vector representation is stored as a dict.
    example: {'key': []}

    Args:
        self: A reference to the current instance of the class. 
        key: The index for retrieval. Indices are strings generated by Faiss.
        embedding: The embedding vector to be stored. 

    """
    def set(self, key, embedding):
        req = embedding_store_pb2.SetRequest()
        req.key = key
        req.embedding.values[:] = embedding
        self._stub.Set(req)

    """Retrieves an embedding record from the storage layer.
    
    Args: 
        self: A reference to the current instance of the class.
        key: The embedding index for retrieval.

    Returns:
        A dict of the embedding vector representation for the corressponding index.  

    """
    def get(self, key):
        resp = self._stub.Get(embedding_store_pb2.GetRequest(key=key))
        return resp.embedding.values

    """Creates mutliple embedding records at once.

    Receives a list of embeddings, iterates over each element and generates a record with a Faiss index.
    example: {'key': []}

    Args: 
        self: A reference to the current instance of the class.
        embedding_dict: A list of embeddings.

    """

    def multiset(self, embedding_dict):
        it = self._embedding_dict_iter(embedding_dict)
        self._stub.MultiSet(it)

    def nearest_neighbor(self, key, num):
        """Finds the given number of nearest neighbor for a given embedding record.\

        Returns 

        Args: 
            self: A reference to the current instance of the class.
            key: The embedding index for retrieval.
            num: The number of nearest neighbors

        Returns:
            A num size list of embedding vectors that are closest to the provided vector embedding.
        """
        req = embedding_store_pb2.NearestNeighborRequest(key=key, num=num)
        return self._stub.NearestNeighbor(req).keys

        """Iterates over a list of embeddings and initalizes an embedding record.

        Args: 
            self: A reference to the current instance of the class.
            embedding_dict: A list of embeddings.

        """
    def _embedding_dict_iter(self, embedding_dict):
        for key, embedding in embedding_dict.items():
            req = embedding_store_pb2.MultiSetRequest()
            req.key = key
            req.embedding.values[:] = embedding
            yield req
