github_checks: false
coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 75%
codecov:
  branch: main
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
