#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
#  Copyright 2024 FeatureForm Inc.
#

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    allowed-values: CN=client
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 64ms
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/issuer: letsencrypt
    {{ if eq .Values.embeddedIngress.enabled false }}
    kots.io/exclude: "true"
    {{ end }}
  name: http-ingress
spec:
  tls:
    - hosts:
        -  {{ .Values.hostname }}
      secretName: {{ .Values.cert.tlsSecretName }}
  defaultBackend:
    service:
      name: featureform-dashboard
      port:
        number: {{ .Values.httpIngressPort }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /data/
            pathType: Prefix
            backend:
              service:
                name: featureform-dashboard-metadata
                port:
                  number: 3001
          - path: /search/
            pathType: Prefix
            backend:
              service:
                name: featureform-dashboard-metadata
                port:
                  number: 3001
          - path: /prometheus/
            pathType: Prefix
            backend:
              service:
                name: featureform-prometheus-service
                port:
                  number: 9090
          - path: /status/
            pathType: Prefix
            backend:
              service:
                name: featureform-api-server
                port:
                  number: 8443
          - path: /
            pathType: Prefix
            backend:
              service:
                name: featureform-dashboard
                port:
                  number: 80
