# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

cc_library(
    name = "embedding_store",
    srcs = [
        "embedding_store_impl.h",
    ],
    hdrs = [
        "embedding_store.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
