name: Publish Quickstart

on:
  push:
    branches:
      - main
    paths:
      - 'quickstart/**'  # Triggers only if files in "quickstart" change

env:
  QUICKSTART_STATIC_FILES_BUCKET_NAME: "featureform-demo-files"

jobs:
  clickhouse:
    name: Build ClickHouse Docker Container
    environment: Deployment
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./quickstart/images/clickhouse/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: featureformcom/quickstart-clickhouse:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  static-files:
    name: Push static files to S3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Push quickstart static files
        run: |
          aws s3 sync quickstart/static_files/ s3://${{ env.QUICKSTART_STATIC_FILES_BUCKET_NAME }}/